config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  resources :s_histories

  resources :staffs

  resources :type_ents do
    collection {post :import }
  end

  resources :job_titles do
    collection {post :import }
  end

  resources :departments do
    collection {post :import }
  end
  
  root to: 'welcome#index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :job_title
  belongs_to :department
  has_one :profiles

  def fullname
    "#{name}, #{surname}"
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:staff_number, :name, :surname, :job_title_id, :department_id, :startdate, :finishdate, :active)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :staff_number %><br>
    <%= f.text_field :staff_number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :job_title_id %><br>
    <%= collection_select( :staff, :job_title_id, JobTitle.all, :id, :description, {}, { :multiple => false } ) %>
  </div>
  <div class="field">
	  <%= f.label :department_id %><br>
	  <%= collection_select( :staff, :department_id, Department.all, :id, :name, {}, { :multiple => false } ) %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :finishdate %><br>
    <%= f.date_select :finishdate %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staffs</h1>

<div class="media">
  <div class="media-body">
  	<table class="table table-hover">
      <thead>
        <tr>
          <th>Staff number</th>
          <th>Name</th>
          <th>Surname</th>
          <th>Job title</th>
          <th>Department</th>
          <th>Startdate</th>
          <th>Finishdate</th>
          <th>Active</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @staffs.each do |staff| %>
          <tr>
            <td><%= staff.staff_number %></td>
            <td><%= staff.name %></td>
            <td><%= staff.surname %></td>
            <td><%= staff.job_title.description %></td>
            <td><%= staff.department.name %></td>
            <td><%= staff.startdate %></td>
            <td><%= staff.finishdate %></td>
            <td><%= staff.active %></td>
            <td><%= link_to 'Show', staff, class: 'btn btn-mini' %></td>
            <td><%= link_to 'Edit', edit_staff_path(staff), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', staff, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Staff number:</strong>
  <%= @staff.staff_number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @staff.surname %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @staff.job_title.description %>
</p>

<p>
  <strong>Department:</strong>
  <%= @staff.department.name %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @staff.startdate %>
</p>

<p>
  <strong>Finishdate:</strong>
  <%= @staff.finishdate %>
</p>

<p>
  <strong>Active:</strong>
  <%= @staff.active %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>