config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  resources :s_histories

  resources :staffs

  resources :type_ents do
    collection {post :import }
  end

  resources :job_titles do
    collection {post :import }
  end

  resources :departments do
    collection {post :import }
  end
  
  root to: 'welcome#index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

end

app/models/s_history.rb
class SHistory < ActiveRecord::Base
  belongs_to :staff
  belongs_to :type_ent
  

end

app/controllers/s_histories_controller.rb
class SHistoriesController < ApplicationController
  require 'my_logger'
  before_filter :authenticate_user!
  before_filter :ensure_admin, :only => [:edit, :destroy]
  before_action :set_s_history, only: [:show, :edit, :update, :destroy]
  # GET /s_histories
  # GET /s_histories.json
  def index
      if current_user.admin? 
        @search = SHistorySearch.new(params[:search])
        @s_histories = @search.scope

      else
        @staffid= Profile.where(:user_id => current_user.id)
        @typeent= TypeEnt.where(:description => "Annual Leave")
        @s_histories = SHistory.where(:staff_id => @staffid, :type_ent => @typeent)
      end

  end

  # GET /s_histories/1
  # GET /s_histories/1.json
  def show
  end

  # GET /s_histories/new
  def new
       @s_history = SHistory.new
  end

  # GET /s_histories/1/edit
  def edit
    
  end

  # POST /s_histories
  # POST /s_histories.json
  def create
    @s_history = SHistory.new(s_history_params)

    respond_to do |format|
      if @s_history.save
        logger = MyLogger.instance
        logger.logInformation("******** History *******")
        logger.logInformation("New History entry: " + @s_history.staff.staff_number + ' - ' + @s_history.staff.name + ',' + @s_history.staff.surname)
        logger.logInformation("entry type: " + @s_history.type_ent.description)

        format.html { redirect_to @s_history, notice: 'Staff history entry was successfully created.' }
        format.json { render :show, status: :created, location: @s_history }
      else
        format.html { render :new }
        format.json { render json: @s_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /s_histories/1
  # PATCH/PUT /s_histories/1.json
  def update
    respond_to do |format|
      if @s_history.update(s_history_params)
        format.html { redirect_to @s_history, notice: 'S history was successfully updated.' }
        format.json { render :show, status: :ok, location: @s_history }
      else
        format.html { render :edit }
        format.json { render json: @s_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /s_histories/1
  # DELETE /s_histories/1.json
  def destroy
    @s_history.destroy
    respond_to do |format|
      format.html { redirect_to s_histories_url, notice: 'S history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def ensure_admin
    unless current_user && current_user.admin?
      render :text => "Access Error Message", :status => :unauthorized
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_s_history
      @s_history = SHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def s_history_params
      params.require(:s_history).permit(:staff_id, :date, :type_ent_id, :ndays, :observation)
    end
end

app/helpers/s_histories_helper.rb
module SHistoriesHelper
end

app/views/s_histories/_form.html.erb
<%= form_for(@s_history) do |f| %>
  <% if @s_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@s_history.errors.count, "error") %> prohibited this s_history from being saved:</h2>

      <ul>
      <% @s_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :staff_id %><br>
    <% if current_user.admin? %>
      <%= collection_select( :s_history, :staff_id, Staff.all, :id, :fullname, {}, { :multiple => false}) %>
    <% else %>
      <%= collection_select( :s_history, :staff_id, Staff.where(:id => (Profile.where(:user_id => current_user.id))), :id, :fullname, {}, { :multiple => false}) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :"Date" %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :type_ent_id %><br>
    <% if current_user.admin? %>
      <%= collection_select( :s_history, :type_ent_id, TypeEnt.all, :id, :description, {}, { :multiple => false }) %>
    <% else %>
     <%= collection_select( :s_history, :type_ent_id, TypeEnt.where(:description => "Annual Leave"), :id, :description, {}, { :multiple => false  }) %>
    <% end %>
    
  </div>
  <div class="field">
    <%= f.label :ndays %><br>
    <%= f.number_field :ndays %>
  </div>
  <div class="field">
    <%= f.label :observation %><br>
    <%= f.text_field :observation %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Entry' %>
  </div>
<% end %>

app/views/s_histories/edit.html.erb
<h1>Editing S History</h1>

<%= render 'form' %>

<%= link_to 'Show', @s_history %> |
<%= link_to 'Back', s_histories_path %>

app/views/s_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staff Entries - Histories</h1>
<% if current_user.admin? %>
  <div class="row">
    <div class="pull-right range-query">
      <%= form_tag s_histories_path, method: :get do %>
        <%= text_field_tag 'search[date_from]', @search.date_from %>
        <%= text_field_tag 'search[date_to]', @search.date_to %>
        <%= submit_tag 'Search', class: 'btn search-button' %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="media">
  <div class="media-body">
  	<table class="table table-hover">
      <thead>
        <tr>
          <th>Staff</th>
          <th>Date</th>
          <th>Type ent</th>
          <th>Number of days</th>
          <th>Observation</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @s_histories.each do |s_history| %>
          <tr>
            <td><%= s_history.staff.staff_number + ' - ' + s_history.staff.name + ',' + s_history.staff.surname %></td>
            <td><%= s_history.date %></td>
            <td><%= s_history.type_ent.description %></td>
            <td><%= s_history.ndays %></td>
            <td><%= s_history.observation %></td>
            <td><%= link_to 'Show', s_history, class: 'btn btn-mini' %></td>
            <td><%= link_to 'Edit', edit_s_history_path(s_history), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', s_history, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Staff - history', new_s_history_path %>

app/views/s_histories/new.html.erb
<h1>New Staff History Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', s_histories_path %>

app/views/s_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Staff:</strong>
  <%= @s_history.staff.name + ',' + @s_history.staff.surname  %>
</p>

<p>
  <strong>Date:</strong>
  <%= @s_history.date %>
</p>

<p>
  <strong>Type entry:</strong>
  <%= @s_history.type_ent.description %>
</p>

<p>
  <strong>Number of days:</strong>
  <%= @s_history.ndays %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @s_history.observation %>
</p>

<%= link_to 'Edit', edit_s_history_path(@s_history) %> |
<%= link_to 'Back', s_histories_path %>