config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  resources :s_histories

  resources :staffs

  resources :type_ents do
    collection {post :import }
  end

  resources :job_titles do
    collection {post :import }
  end

  resources :departments do
    collection {post :import }
  end
  
  root to: 'welcome#index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

end

app/models/type_ent.rb
class TypeEnt < ActiveRecord::Base
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            TypeEnt.create! row.to_hash
        end
    end
end

app/controllers/type_ents_controller.rb
class TypeEntsController < ApplicationController
  before_action :set_type_ent, only: [:show, :edit, :update, :destroy]

  # GET /type_ents
  # GET /type_ents.json
  def index
    @type_ents = TypeEnt.all
  end

  # GET /type_ents/1
  # GET /type_ents/1.json
  def show
  end

  # GET /type_ents/new
  def new
    @type_ent = TypeEnt.new
  end

  # GET /type_ents/1/edit
  def edit
  end

  # POST /type_ents
  # POST /type_ents.json
  def create
    @type_ent = TypeEnt.new(type_ent_params)

    respond_to do |format|
      if @type_ent.save
        format.html { redirect_to @type_ent, notice: 'Type ent was successfully created.' }
        format.json { render :show, status: :created, location: @type_ent }
      else
        format.html { render :new }
        format.json { render json: @type_ent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_ents/1
  # PATCH/PUT /type_ents/1.json
  def update
    respond_to do |format|
      if @type_ent.update(type_ent_params)
        format.html { redirect_to @type_ent, notice: 'Type ent was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_ent }
      else
        format.html { render :edit }
        format.json { render json: @type_ent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_ents/1
  # DELETE /type_ents/1.json
  def destroy
    @type_ent.destroy
    respond_to do |format|
      format.html { redirect_to type_ents_url, notice: 'Type ent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    TypeEnt.import(params[:file])
    redirect_to type_ents_url, notice: "Entry Types Added Successfully"
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_ent
      @type_ent = TypeEnt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_ent_params
      params.require(:type_ent).permit(:initial, :description)
    end
end

app/helpers/type_ents_helper.rb
module TypeEntsHelper
end

app/views/type_ents/_form.html.erb
<%= form_for(@type_ent) do |f| %>
  <% if @type_ent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type_ent.errors.count, "error") %> prohibited this type_ent from being saved:</h2>

      <ul>
      <% @type_ent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :initial %><br>
    <%= f.text_field :initial %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/type_ents/edit.html.erb
<h1>Editing Entry Types</h1>

<%= render 'form' %>

<%= link_to 'Show', @type_ent %> |
<%= link_to 'Back', type_ents_path %>

app/views/type_ents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entry Types</h1>

<div class="media">
  <div class="media-body">
  	<table class="table table-hover">
      <thead>
        <tr>
          <th>Initial</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @type_ents.each do |type_ent| %>
          <tr>
            <td><%= type_ent.initial %></td>
            <td><%= type_ent.description %></td>
            <td><%= link_to 'Show', type_ent, class: 'btn btn-mini' %></td>
            <td><%= link_to 'Edit', edit_type_ent_path(type_ent), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', type_ent, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<h3>Import Entry Types</h3>
<%= form_tag import_type_ents_path, multipart: true do %>
  <%= file_field_tag :file %> <br>
  <%= submit_tag "Upload Entry Types" %>
<% end %>

<%= link_to 'New Entry Type', new_type_ent_path %>

app/views/type_ents/new.html.erb
<h1>New Entry Type</h1>

<%= render 'form' %>

<%= link_to 'Back', type_ents_path %>

app/views/type_ents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Initial:</strong>
  <%= @type_ent.initial %>
</p>

<p>
  <strong>Description:</strong>
  <%= @type_ent.description %>
</p>

<%= link_to 'Edit', edit_type_ent_path(@type_ent) %> |
<%= link_to 'Back', type_ents_path %>