config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  resources :s_histories

  resources :staffs

  resources :type_ents do
    collection {post :import }
  end

  resources :job_titles do
    collection {post :import }
  end

  resources :departments do
    collection {post :import }
  end
  
  root to: 'welcome#index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

end

app/models/job_title.rb
class JobTitle < ActiveRecord::Base
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            JobTitle.create! row.to_hash
        end
    end
end

app/controllers/job_titles_controller.rb
class JobTitlesController < ApplicationController
  before_action :set_job_title, only: [:show, :edit, :update, :destroy]

  # GET /job_titles
  # GET /job_titles.json
  def index
    @job_titles = JobTitle.all
  end

  # GET /job_titles/1
  # GET /job_titles/1.json
  def show
  end

  # GET /job_titles/new
  def new
    @job_title = JobTitle.new
  end

  # GET /job_titles/1/edit
  def edit
  end

  # POST /job_titles
  # POST /job_titles.json
  def create
    @job_title = JobTitle.new(job_title_params)

    respond_to do |format|
      if @job_title.save
        format.html { redirect_to @job_title, notice: 'Job title was successfully created.' }
        format.json { render :show, status: :created, location: @job_title }
      else
        format.html { render :new }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_titles/1
  # PATCH/PUT /job_titles/1.json
  def update
    respond_to do |format|
      if @job_title.update(job_title_params)
        format.html { redirect_to @job_title, notice: 'Job title was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_title }
      else
        format.html { render :edit }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_titles/1
  # DELETE /job_titles/1.json
  def destroy
    @job_title.destroy
    respond_to do |format|
      format.html { redirect_to job_titles_url, notice: 'Job title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    JobTitle.import(params[:file])
    redirect_to job_titles_url, notice: "Job Titles Added Successfully"
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_title
      @job_title = JobTitle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_title_params
      params.require(:job_title).permit(:description)
    end
end

app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

app/views/job_titles/_form.html.erb
<%= form_for(@job_title) do |f| %>
  <% if @job_title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_title.errors.count, "error") %> prohibited this job_title from being saved:</h2>

      <ul>
      <% @job_title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_titles/edit.html.erb
<h1>Editing Job Title</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_title %> |
<%= link_to 'Back', job_titles_path %>

app/views/job_titles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Job Titles</h1>

<div class="media">
  <div class="media-body">
  	<table class="table table-hover">
      <thead>
        <tr>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @job_titles.each do |job_title| %>
          <tr>
            <td><%= job_title.description %></td>
            <td><%= link_to 'Show', job_title, class: 'btn btn-mini' %></td>
            <td><%= link_to 'Edit', edit_job_title_path(job_title), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', job_title, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<h3>Import Job Titles</h3>
<%= form_tag import_job_titles_path, multipart: true do %>
  <%= file_field_tag :file %> <br>
  <%= submit_tag "Upload Job Titles" %>
<% end %>
<br>
<%= link_to 'New Job title', new_job_title_path %>

app/views/job_titles/new.html.erb
<h1>New Job Title</h1>

<%= render 'form' %>

<%= link_to 'Back', job_titles_path %>

app/views/job_titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @job_title.description %>
</p>

<%= link_to 'Edit', edit_job_title_path(@job_title) %> |
<%= link_to 'Back', job_titles_path %>